//USER TYPES
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER = "SET_USER";

//EXAM PAPER TYPES
export const LOAD_EXAM_PAPERS = "LOAD_EXAM_PAPERS";
export const LOAD_EXAM_PAPERS_SUCCESSFUL = "LOAD_EXAM_PAPERS_SUCCESSFUL";
export const LOAD_EXAM_PAPERS_FAILURE = "LOAD_EXAM_PAPERS_FAILURE";
export const CLEAR_EXAM_PAPERS = "CLEAR_EXAM_PAPERS";

export const LOAD_SELECTED_QUESTION_SUCCESSFUL = "LOAD_SELECTED_QUESTION_SUCCESSFUL";
export const LOAD_SELECTED_QUESTION_FAILURE = "LOAD_SELECTED_QUESTION_FAILURE";

export const LOAD_SELECTED_EXAM_PAPER_SUCCESSFUL = "LOAD_SELECTED_EXAM_PAPER_SUCCESSFUL";
export const LOAD_SELECTED_EXAM_PAPER_FAILURE = "LOAD_SELECTED_EXAM_PAPER_FAILURE";

//QUESTION TYPES
export const LOAD_QUESTIONS = "QUESTIONS_LOAD";
export const LOAD_QUESTIONS_SUCCESSFUL = "LOAD_QUESTIONS_SUCCESSFUL";
export const LOAD_QUESTIONS_FAILURE = "LOAD_QUESTIONS_FAILURE";
export const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";

export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_QUESTION_SUCCESSFUL = "ADD_QUESTION_SUCCESSFUL";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";

export const LOAD_EXAM_PAPER = "LOAD_EXAM_PAPER";
export const LOAD_EXAM_PAPER_SUCCESSFUL = "LOAD_EXAM_PAPER_SUCCESSFUL";
export const LOAD_EXAM_PAPER_FAILURE = "LOAD_EXAM_PAPER_FAILURE";

//ANSWERS TYPES
export const LOAD_ANSWERS = "LOAD_ANSWERS";
export const LOAD_ANSWERS_SUCCESSFUL = "LOAD_ANSWERS_SUCCESSFUL";
export const LOAD_ANSWERS_FAILURE = "LOAD_ANSWERS_FAILURE";
export const CLEAR_ANSWERS = "CLEAR_ANSWERS";

export const ADD_ANSWER = "ADD_ANSWER";
export const ADD_ANSWER_SUCCESSFUL = "ADD_ANSWER_SUCCESSFUL";
export const ADD_ANSWER_FAILURE = "ADD_ANSWER_FAILURE";

//PROFILE TYPES
export const LOAD_PROFILE = "LOAD_PROFILE";
export const LOAD_PROFILE_SUCCESSFUL = "LOAD_PROFILE_SUCCESSFUL";
export const LOAD_PROFILE_FAILURE = "LOAD_PROFILE_FAILURE";
export const SET_MY_PROFILE = "SET_MY_PROFILE";
export const CHANGE_USERNAME_AVATAR = "CHANGE_USERNAME_AVATAR";

//COURSE TYPES
export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";
export const ADD_COURSE_SUCCESSFUL = "ADD_COURSE_SUCCESSFUL";
export const SET_COURSE_MESSAGE = "SET_COURSE_MESSAGE";
